### ISSUE TITLE
Arch: cannot build

### ISSUE THREAD

**Issue by Hebgbs** [zhuyaliang/group-service#7]
Same issue as #6. Attempting to build with `makepkg` after having download this package via AUR fails.

Can anyone else using Arch confirm this issue, and what possible fix can be performed? I am using MATE and I want to install `user-admin` but it depends on this.

**Comment by zhuyaliang** [comment]
What is your build process like? It can be built normally in my ```Arch```

**Comment by rekitheduck** [comment]
@Hebgbs is trying to install the AUR package https://aur.archlinux.org/packages/user-admin which uses version 1.3.0 from this repository. However, the fix for the crash was made after that version. A fix would be to both bump the version here and then update which version the AUR package uses

**Comment by Hebgbs** [comment]
Can affirm use of AUR.
```
git clone https://github.com/zhuyaliang/group-service.git
cd ./group-service
makepkg -si
```
Duck is a friend of mine wanting to take it upon himself to ensure the AUR package functions as he is rather enthusiastic about the MATE desktop. I understand you may not be responsible for it, and I apologize for any inconvenience I may had caused.

Best of luck to you @rekitheduck!

**Comment by zhuyaliang** [comment]
I updated the new version [1.4.0](https://github.com/zhuyaliang/group-service/releases/tag/1.4.0) ，https://github.com/zhuyaliang/group-service/releases/tag/1.4.0

**Comment by rekitheduck** [comment]
Thanks. I've updated the AUR package for both this and `user-admin` and had @Hebgbs test it. So this issue can be closed

**Comment by Hebgbs** [comment]
`user-admin` also had issues Duck resolved..
